### ISSUE TITLE
Test if "Rochade" & "En passant" etc. is recognized as legal move

### ISSUE THREAD

**Issue by PascalSchroederDE** [StudienarbeitLarsPascal/LibraryEvaluation#6]

**Comment by PascalSchroederDE** [comment]
If moves are not recognized as legal moves, try to write a function which checks for legal en_passant / rochade etc. with functions like:
board.has_legal_en_passant
board.is_en_passant
board.has_castling_rights
board.is_kingside_castling
board.is_queenside_castling
[...]

**Comment by larsdittert** [comment]
SVG rendering: compute and visualize possible attacks (pawn, en passant)
